
FR:
    prefix: 33
    regex:
        - "/33(06|07)[0-9]{8}/"


US:
    prefix: 1
    regex:
        - "/1[0-9]{10}/"

GB:
    prefix: 44
    regex:
        - "/4407(4|5|6|7|8|9)[0-9]{8}/" # consoldated the regex below: 
#        - "/44074[0-9]{8}/" # 070 xxxx xxxx	Personal Numbering & xx xxxxxx	Mobile phones (in use since November 2009)
#        - "/44075[0-9]{8}/" # 075xx xxxxxx	Mobile phones (in use since May 2007)
#        - "/44076[0-9]{8}/" # 076 xxxx xxxx	Pagers (excluding 07624, used for mobile phones on the Isle of Man)
#        - "/44077[0-9]{8}/" # 077xx xxxxxx	Mobile phones (former 03xx and 04xx—mostly Vodafone and O2 (formerly Cellnet))
#        - "/44078[0-9]{8}/" # 078xx xxxxxx	Mobile phones (former 05xx, 06xx and 08xx—mostly Vodafone and O2 (formerly Cellnet))
#        - "/44079[0-9]{8}/" # 079xx xxxxxx	Mobile phones (former 09xx—mostly Orange and T-Mobile (formerly one2one))
